### ISSUE TITLE
Tasmota variation - unknown state doesnt work

### ISSUE THREAD

**Issue by jaygrovr** [aderusha/MQTTCarPresence#22]
hey there, I just got everything setup and it works with the tasmota variation, except when the d1 mini goes offline, HA reports the state as unknown and the garage door never closes.  Is there a way to fix that?

Thanks
Jason

**Comment by SirGoodenough** [comment]
If your device shows as unknown, you may need to change the 'unavailable' in the blueprint to 'unknown'.
It shows up in 2 places.

```yaml
trigger:
  - platform: state
    entity_id: !input car_presence
    to: 'on'
  - platform: state
    entity_id: !input car_presence
    to: 'unavailable'
    for:
      minutes: 1
```

AND

```yaml
      - conditions:
          - condition: state
            entity_id: !input car_presence
            state: 'unavailable'
          - condition: state
            entity_id: !input garage_door
            state: open
```
